In [668]:
from sklearn.linear_model import LogisticRegression

In [669]:
lr = LogisticRegression(
    max_iter=1000
)

In [670]:
from sklearn.model_selection import train_test_split

In [671]:
import pandas as pd

df = pd.read_csv("../data/processed/cleaned_telco.csv")

In [672]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [673]:
df["Churn"] = df["Churn"].map({
    "No":0,
    "Yes":1
})

In [674]:
df_encoded = pd.get_dummies(
    df,
    drop_first=True
)

In [675]:
X = df_encoded.drop(
    "Churn",
    axis=1
)

y = df_encoded["Churn"]

In [676]:
print(X.shape)
print(y.shape)

(7043, 30)
(7043,)

In [677]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [678]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(5634, 30)
(1409, 30)
(5634,)
(1409,)

In [679]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [680]:
X_train_scaled = scaler.fit_transform(
    X_train
)

X_test_scaled = scaler.transform(
    X_test
)

In [681]:
print(X_train_scaled.shape)
print(X_test_scaled.shape)

(5634, 30)
(1409, 30)

In [682]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(
    max_iter=1000
)

In [683]:
lr.fit(
    X_train_scaled,
    y_train
)

LogisticRegression(max_iter=1000)

In [684]:
lr_pred = lr.predict(
    X_test_scaled
)

In [685]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(
    y_test,
    lr_pred
)

print(accuracy)

0.8069552874378992

In [686]:
dir()

['DecisionTreeClassifier',
 'In',
 'LogisticRegression',
 'Out',
 'RandomForestClassifier',
 'StandardScaler',
 'X',
 'XGBClassifier',
 'X_test',
 'X_test_scaled',
 'X_train',
 'X_train_scaled',
 '_',
 '_111',
 '_125',
 '_140',
 '_151',
 '_156',
 '_167',
 '_173',
 '_184',
 '_19',
 '_191',
 '_202',
 '_205',
 '_210',
 '_221',
 '_224',
 '_230',
 '_24',
 '_241',
 '_244',
 '_251',
 '_262',
 '_265',
 '_268',
 '_273',
 '_284',
 '_287',
 '_290',
 '_296',
 '_30',
 '_307',
 '_310',
 '_313',
 '_320',
 '_331',
 '_334',
 '_337',
 '_345',
 '_356',
 '_359',
 '_362',
 '_366',
 '_37',
 '_371',
 '_382',
 '_385',
 '_388',
 '_392',
 '_398',
 '_409',
 '_412',
 '_415',
 '_419',
 '_426',
 '_437',
 '_440',
 '_443',
 '_447',
 '_45',
 '_454',
 '_465',
 '_468',
 '_471',
 '_475',
 '_482',
 '_493',
 '_496',
 '_499',
 '_503',
 '_511',
 '_522',
 '_525',
 '_528',
 '_532',
 '_54',
 '_541',
 '_552',
 '_555',
 '_558',
 '_562',
 '_567',
 '_572',
 '_583',
 '_586',
 '_589',
 '_593',
 '_598',
 '_604',
 '_615',
 '_618',
 '_621',
 '_625',
 '_630',
 '_638',
 '_64',
 '_649',
 '_652',
 '_655',
 '_659',
 '_664',
 '_672',
 '_683',
 '_75',
 '_86',
 '_98',
 '__',
 '___',
 '__builtin__',
 '__builtins__',
 '__doc__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '__vsc_ipynb_file__',
 '_dh',
 '_exit_code',
 '_i',
 '_i1',
 '_i10',
 '_i100',
 '_i101',
 '_i102',
 '_i103',
 '_i104',
 '_i105',
 '_i106',
 '_i107',
 '_i108',
 '_i109',
 '_i11',
 '_i110',
 '_i111',
 '_i112',
 '_i113',
 '_i114',
 '_i115',
 '_i116',
 '_i117',
 '_i118',
 '_i119',
 '_i12',
 '_i120',
 '_i121',
 '_i122',
 '_i123',
 '_i124',
 '_i125',
 '_i126',
 '_i127',
 '_i128',
 '_i129',
 '_i13',
 '_i130',
 '_i131',
 '_i132',
 '_i133',
 '_i134',
 '_i135',
 '_i136',
 '_i137',
 '_i138',
 '_i139',
 '_i14',
 '_i140',
 '_i141',
 '_i142',
 '_i143',
 '_i144',
 '_i145',
 '_i146',
 '_i147',
 '_i148',
 '_i149',
 '_i15',
 '_i150',
 '_i151',
 '_i152',
 '_i153',
 '_i154',
 '_i155',
 '_i156',
 '_i157',
 '_i158',
 '_i159',
 '_i16',
 '_i160',
 '_i161',
 '_i162',
 '_i163',
 '_i164',
 '_i165',
 '_i166',
 '_i167',
 '_i168',
 '_i169',
 '_i17',
 '_i170',
 '_i171',
 '_i172',
 '_i173',
 '_i174',
 '_i175',
 '_i176',
 '_i177',
 '_i178',
 '_i179',
 '_i18',
 '_i180',
 '_i181',
 '_i182',
 '_i183',
 '_i184',
 '_i185',
 '_i186',
 '_i187',
 '_i188',
 '_i189',
 '_i19',
 '_i190',
 '_i191',
 '_i192',
 '_i193',
 '_i194',
 '_i195',
 '_i196',
 '_i197',
 '_i198',
 '_i199',
 '_i2',
 '_i20',
 '_i200',
 '_i201',
 '_i202',
 '_i203',
 '_i204',
 '_i205',
 '_i206',
 '_i207',
 '_i208',
 '_i209',
 '_i21',
 '_i210',
 '_i211',
 '_i212',
 '_i213',
 '_i214',
 '_i215',
 '_i216',
 '_i217',
 '_i218',
 '_i219',
 '_i22',
 '_i220',
 '_i221',
 '_i222',
 '_i223',
 '_i224',
 '_i225',
 '_i226',
 '_i227',
 '_i228',
 '_i229',
 '_i23',
 '_i230',
 '_i231',
 '_i232',
 '_i233',
 '_i234',
 '_i235',
 '_i236',
 '_i237',
 '_i238',
 '_i239',
 '_i24',
 '_i240',
 '_i241',
 '_i242',
 '_i243',
 '_i244',
 '_i245',
 '_i246',
 '_i247',
 '_i248',
 '_i249',
 '_i25',
 '_i250',
 '_i251',
 '_i252',
 '_i253',
 '_i254',
 '_i255',
 '_i256',
 '_i257',
 '_i258',
 '_i259',
 '_i26',
 '_i260',
 '_i261',
 '_i262',
 '_i263',
 '_i264',
 '_i265',
 '_i266',
 '_i267',
 '_i268',
 '_i269',
 '_i27',
 '_i270',
 '_i271',
 '_i272',
 '_i273',
 '_i274',
 '_i275',
 '_i276',
 '_i277',
 '_i278',
 '_i279',
 '_i28',
 '_i280',
 '_i281',
 '_i282',
 '_i283',
 '_i284',
 '_i285',
 '_i286',
 '_i287',
 '_i288',
 '_i289',
 '_i29',
 '_i290',
 '_i291',
 '_i292',
 '_i293',
 '_i294',
 '_i295',
 '_i296',
 '_i297',
 '_i298',
 '_i299',
 '_i3',
 '_i30',
 '_i300',
 '_i301',
 '_i302',
 '_i303',
 '_i304',
 '_i305',
 '_i306',
 '_i307',
 '_i308',
 '_i309',
 '_i31',
 '_i310',
 '_i311',
 '_i312',
 '_i313',
 '_i314',
 '_i315',
 '_i316',
 '_i317',
 '_i318',
 '_i319',
 '_i32',
 '_i320',
 '_i321',
 '_i322',
 '_i323',
 '_i324',
 '_i325',
 '_i326',
 '_i327',
 '_i328',
 '_i329',
 '_i33',
 '_i330',
 '_i331',
 '_i332',
 '_i333',
 '_i334',
 '_i335',
 '_i336',
 '_i337',
 '_i338',
 '_i339',
 '_i34',
 '_i340',
 '_i341',
 '_i342',
 '_i343',
 '_i344',
 '_i345',
 '_i346',
 '_i347',
 '_i348',
 '_i349',
 '_i35',
 '_i350',
 '_i351',
 '_i352',
 '_i353',
 '_i354',
 '_i355',
 '_i356',
 '_i357',
 '_i358',
 '_i359',
 '_i36',
 '_i360',
 '_i361',
 '_i362',
 '_i363',
 '_i364',
 '_i365',
 '_i366',
 '_i367',
 '_i368',
 '_i369',
 '_i37',
 '_i370',
 '_i371',
 '_i372',
 '_i373',
 '_i374',
 '_i375',
 '_i376',
 '_i377',
 '_i378',
 '_i379',
 '_i38',
 '_i380',
 '_i381',
 '_i382',
 '_i383',
 '_i384',
 '_i385',
 '_i386',
 '_i387',
 '_i388',
 '_i389',
 '_i39',
 '_i390',
 '_i391',
 '_i392',
 '_i393',
 '_i394',
 '_i395',
 '_i396',
 '_i397',
 '_i398',
 '_i399',
 '_i4',
 '_i40',
 '_i400',
 '_i401',
 '_i402',
 '_i403',
 '_i404',
 '_i405',
 '_i406',
 '_i407',
 '_i408',
 '_i409',
 '_i41',
 '_i410',
 '_i411',
 '_i412',
 '_i413',
 '_i414',
 '_i415',
 '_i416',
 '_i417',
 '_i418',
 '_i419',
 '_i42',
 '_i420',
 '_i421',
 '_i422',
 '_i423',
 '_i424',
 '_i425',
 '_i426',
 '_i427',
 '_i428',
 '_i429',
 '_i43',
 '_i430',
 '_i431',
 '_i432',
 '_i433',
 '_i434',
 '_i435',
 '_i436',
 '_i437',
 '_i438',
 '_i439',
 '_i44',
 '_i440',
 '_i441',
 '_i442',
 '_i443',
 '_i444',
 '_i445',
 '_i446',
 '_i447',
 '_i448',
 '_i449',
 '_i45',
 '_i450',
 '_i451',
 '_i452',
 '_i453',
 '_i454',
 '_i455',
 '_i456',
 '_i457',
 '_i458',
 '_i459',
 '_i46',
 '_i460',
 '_i461',
 '_i462',
 '_i463',
 '_i464',
 '_i465',
 '_i466',
 '_i467',
 '_i468',
 '_i469',
 '_i47',
 '_i470',
 '_i471',
 '_i472',
 '_i473',
 '_i474',
 '_i475',
 '_i476',
 '_i477',
 '_i478',
 '_i479',
 '_i48',
 '_i480',
 '_i481',
 '_i482',
 '_i483',
 '_i484',
 '_i485',
 '_i486',
 '_i487',
 '_i488',
 '_i489',
 '_i49',
 '_i490',
 '_i491',
 '_i492',
 '_i493',
 '_i494',
 '_i495',
 '_i496',
 '_i497',
 '_i498',
 '_i499',
 '_i5',
 '_i50',
 '_i500',
 '_i501',
 '_i502',
 '_i503',
 '_i504',
 '_i505',
 '_i506',
 '_i507',
 '_i508',
 '_i509',
 '_i51',
 '_i510',
 '_i511',
 '_i512',
 '_i513',
 '_i514',
 '_i515',
 '_i516',
 '_i517',
 '_i518',
 '_i519',
 '_i52',
 '_i520',
 '_i521',
 '_i522',
 '_i523',
 '_i524',
 '_i525',
 '_i526',
 '_i527',
 '_i528',
 '_i529',
 '_i53',
 '_i530',
 '_i531',
 '_i532',
 '_i533',
 '_i534',
 '_i535',
 '_i536',
 '_i537',
 '_i538',
 '_i539',
 '_i54',
 '_i540',
 '_i541',
 '_i542',
 '_i543',
 '_i544',
 '_i545',
 '_i546',
 '_i547',
 '_i548',
 '_i549',
 '_i55',
 '_i550',
 '_i551',
 '_i552',
 '_i553',
 '_i554',
 '_i555',
 '_i556',
 '_i557',
 '_i558',
 '_i559',
 '_i56',
 '_i560',
 '_i561',
 '_i562',
 '_i563',
 '_i564',
 '_i565',
 '_i566',
 '_i567',
 '_i568',
 '_i569',
 '_i57',
 '_i570',
 '_i571',
 '_i572',
 '_i573',
 '_i574',
 '_i575',
 '_i576',
 '_i577',
 '_i578',
 '_i579',
 '_i58',
 '_i580',
 '_i581',
 '_i582',
 '_i583',
 '_i584',
 '_i585',
 '_i586',
 '_i587',
 '_i588',
 '_i589',
 '_i59',
 '_i590',
 '_i591',
 '_i592',
 '_i593',
 '_i594',
 '_i595',
 '_i596',
 '_i597',
 '_i598',
 '_i599',
 '_i6',
 '_i60',
 '_i600',
 '_i601',
 '_i602',
 '_i603',
 '_i604',
 '_i605',
 '_i606',
 '_i607',
 '_i608',
 '_i609',
 '_i61',
 '_i610',
 '_i611',
 '_i612',
 '_i613',
 '_i614',
 '_i615',
 '_i616',
 '_i617',
 '_i618',
 '_i619',
 '_i62',
 '_i620',
 '_i621',
 '_i622',
 '_i623',
 '_i624',
 '_i625',
 '_i626',
 '_i627',
 '_i628',
 '_i629',
 '_i63',
 '_i630',
 '_i631',
 '_i632',
 '_i633',
 '_i634',
 '_i635',
 '_i636',
 '_i637',
 '_i638',
 '_i639',
 '_i64',
 '_i640',
 '_i641',
 '_i642',
 '_i643',
 '_i644',
 '_i645',
 '_i646',
 '_i647',
 '_i648',
 '_i649',
 '_i65',
 '_i650',
 '_i651',
 '_i652',
 '_i653',
 '_i654',
 '_i655',
 '_i656',
 '_i657',
 '_i658',
 '_i659',
 '_i66',
 '_i660',
 '_i661',
 '_i662',
 '_i663',
 '_i664',
 '_i665',
 '_i666',
 '_i667',
 '_i668',
 '_i669',
 '_i67',
 '_i670',
 '_i671',
 '_i672',
 '_i673',
 '_i674',
 '_i675',
 '_i676',
 '_i677',
 '_i678',
 '_i679',
 '_i68',
 '_i680',
 '_i681',
 '_i682',
 '_i683',
 '_i684',
 '_i685',
 '_i686',
 '_i69',
 '_i7',
 '_i70',
 '_i71',
 '_i72',
 '_i73',
 '_i74',
 '_i75',
 '_i76',
 '_i77',
 '_i78',
 '_i79',
 '_i8',
 '_i80',
 '_i81',
 '_i82',
 '_i83',
 '_i84',
 '_i85',
 '_i86',
 '_i87',
 '_i88',
 '_i89',
 '_i9',
 '_i90',
 '_i91',
 '_i92',
 '_i93',
 '_i94',
 '_i95',
 '_i96',
 '_i97',
 '_i98',
 '_i99',
 '_ih',
 '_ii',
 '_iii',
 '_oh',
 'accuracy',
 'accuracy_score',
 'df',
 'df_encoded',
 'dt',
 'dt_pred',
 'evaluate_model',
 'exit',
 'f1_score',
 'get_ipython',
 'lr',
 'lr_pred',
 'open',
 'pd',
 'precision_score',
 'quit',
 'recall_score',
 'rf',
 'rf_pred',
 'scaler',
 'sys',
 'train_test_split',
 'xgb',
 'xgb_pred',
 'y',
 'y_test',
 'y_train']

In [687]:
from sklearn.tree import DecisionTreeClassifier

In [688]:
dt = DecisionTreeClassifier(
    random_state=42
)

In [689]:
dt.fit(
    X_train,
    y_train
)

DecisionTreeClassifier(random_state=42)

In [690]:
dt_pred = dt.predict(
    X_test
)

In [691]:
from sklearn.ensemble import RandomForestClassifier

In [692]:
rf = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

In [693]:
rf.fit(
    X_train,
    y_train
)

RandomForestClassifier(n_estimators=200, random_state=42)

In [694]:
rf_pred = rf.predict(
    X_test
)

In [695]:
import sys

!{sys.executable} -m pip install xgboost

Requirement already satisfied: xgboost in c:\users\asus\anaconda3\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\asus\anaconda3\lib\site-packages (from xgboost) (2.3.5)
Requirement already satisfied: scipy in c:\users\asus\anaconda3\lib\site-packages (from xgboost) (1.16.3)

In [696]:
from xgboost import XGBClassifier

In [697]:
xgb = XGBClassifier(
    random_state=42
)

In [698]:
xgb.fit(
    X_train,
    y_train
)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=None,
              n_jobs=None, num_parallel_tree=None, ...)

In [699]:
xgb_pred = xgb.predict(
    X_test
)

MODAL COMPARSION

In [700]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score
)

In [701]:
def evaluate_model(
    y_true,
    y_pred,
    model_name
):
    return {
        "Model":model_name,
        "Accuracy":accuracy_score(
            y_true,
            y_pred
        ),
        "Precision":precision_score(
            y_true,
            y_pred
        ),
        "Recall":recall_score(
            y_true,
            y_pred
        ),
        "F1":f1_score(
            y_true,
            y_pred
        )
    }

In [702]:
results = pd.DataFrame([
    evaluate_model(
        y_test,
        lr_pred,
        "Logistic Regression"
    ),
    evaluate_model(
        y_test,
        dt_pred,
        "Decision Tree"
    ),
    evaluate_model(
        y_test,
        rf_pred,
        "Random Forest"
    ),
    evaluate_model(
        y_test,
        xgb_pred,
        "XGBoost"
    )
])

results

                 Model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.806955   0.658385  0.566845  0.609195
1        Decision Tree  0.741661   0.513889  0.494652  0.504087
2        Random Forest  0.789922   0.633562  0.494652  0.555556
3              XGBoost  0.784954   0.607903  0.534759  0.568990